### ISSUE TITLE
HW about Zero Activity from 03.10.16

### ISSUE THREAD

**Issue by AlexTheKing** [deniotokiari/training-epam-2016#10]
New repo with homework:
https://github.com/AlexTheKing/HW-03-10-2016

**Comment by ilya-shknaj** [comment]
Bad solution override method onBackPressed and start new activity every time, because 
1) you will have a lot of instances Activity in backstack.
2) In real application you don't know previous activity.
Stop override onBackPressed method and start use flags
https://developer.android.com/reference/android/content/Intent.html#

Also try extract duplicate code to some util class (for instance work with preferences) and use constants instead of hardcode

**Comment by AlexTheKing** [comment]
Thank you for your comment. I don't understand a little bit, should this App normally work if "Don't keep activities" option in developer settings is on?
As I see, if this option is on, then some of HWs, that you accepted, will not work.
Or did I miss something?
I created new branch, named "withoutOption", so there is a version if backstack works properly (without "Don't keep activities" option, as I understand).
New branch:  https://github.com/AlexTheKing/HW-03-10-2016/tree/withoutOption

**Comment by ilya-shknaj** [comment]
@AlexTheKing It depends of logic of your application.
1) If user foreground application on SecondActivity  (activity destroyed) and he reopen application again, it's could be ok if he again see first screen.
2) If user foreground application on SecondActivity  (activity destroyed) and he reopen application again, it's better that first case.

If user finish login flow, foreground application (activity destroyed) and reopen it again, it's wrong if he see first screen.
Also wrong solution override onBackPressedMethod.

Now implementation is right.
If you have additional questions feel free to ask about that on next lesson.
