### ISSUE TITLE
HW: ZeroActivity 05.10.2016

### ISSUE THREAD

**Issue by ivan-kudziev** [deniotokiari/training-epam-2016#20]
https://github.com/ifire777/android_training_E2016

**Comment by ilya-shknaj** [comment]
1) bad solution save some value in static variable of activity and read/write that value from another activities. Use preferences
2) Bad solution override onBackPressed method and call some activity on that method, because in real application you can't know previous activity
3) Strange solution save String to preference, read string and after that convert to integer

**Comment by ivan-kudziev** [comment]
1)removed static fields (as i understand we don't use static because it can be destroyed by system in any time, so no static in android apps?)
2)removed.
